import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Navbar from '@/components/Navbar'
import { Main } from '@/components/Main'
import { About } from '@/components/About'
import { Skills } from '@/components/Skills'
import { Projects } from '@/components/Projects'
import Contact from '@/components/Contact'
import { DataType } from '@/utils/type'

type Props ={
  data:DataType
}


export default function Home({data}:Props) {
  
 
  return (
    <>
      <Head>
        <title>Iman Kamrava</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Navbar/>
        <Main/>
        <About/>
        <Skills/>
        <Projects data={data}/>
        <Contact/>
      </main>
    </>
  )
}


export async function getServerSideProps() {
  const  {projectsData}  = await import('utils/projectinfo.json');


  return {
    props: {
      data: projectsData,
    },
  };
}